---
services:
    ezplatform.udw.image.panel.module.js:
        parent: EzSystems\EzPlatformAdminUi\Component\ScriptComponent
        arguments:
            $src: /bundles/ezsystemsextendingtutorial/js/modules/ImagesPanel.module.js
        tags:
            - { name: ezplatform.admin_ui.component, group: custom-admin-ui-modules }

    ezplatform.udw.add.tab.js:
        parent: EzSystems\EzPlatformAdminUi\Component\ScriptComponent
        arguments:
            $src: /bundles/ezsystemsextendingtutorial/js/add.tab.js
        tags:
            - { name: ezplatform.admin_ui.component, group: custom-admin-ui-config }